#! /usr/bin/env python2
# -*- coding: utf8 -*-
import dmenu_extended
import sys

def run(argv):
    if '-v' in argv:
        debug = True
    else:
        debug = False

    d = dmenu_extended.dmenu()
    d.cache_regenerate(debug, message=False)


if __name__ == '__main__':
    run(sys.argv[1:])
