#! /usr/bin/env python
# -*- coding: utf8 -*-
import dmenu_extended
import sys

if __name__ == '__main__':
    debug = False
    if '--debug' in sys.argv:
        print('Debugging enabled')
        debug = True
    dmenu_extended.run(debug)