name: Continuous Integration
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  System test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build test image
      run: ./test.sh --build
    - name: Run system test
      run: ./test.sh --full
