name: Continuous Integration
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: System Test
      run: ls && cd dmenu-extended && ls && ./test.sh --full
